name: release

on:
  push:
    branches:    
      - master
    tags:        
      - v*

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master

    - name: Download Build Tools for Visual Studio 2019
      if: matrix.os == 'windows-latest'
      run: Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

    - name: Run vs_buildtools.exe install
      if: matrix.os == 'windows-latest'
      run: ./vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.140 --includeRecommended

    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Python package dependencies
      run: pip install cython wheel

    - name: Build binary wheel
      run: python setup.py bdist_wheel

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create source dist
      run: python setup.py sdist

    - name: Stage windows-latest 3.5
      uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest-3.5
    - run: mv dist-windows-latest-3.5/* dist/

    - name: Stage windows-latest 3.6
      uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest-3.6
    - run: mv dist-windows-latest-3.6/* dist/

    - name: Stage windows-latest 3.7
      uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest-3.7
    - run: mv dist-windows-latest-3.7/* dist/

    - name: Stage windows-latest 3.8
      uses: actions/download-artifact@v1
      with:
        name: dist-windows-latest-3.8
    - run: mv dist-windows-latest-3.8/* dist/

    - name: Stage ubuntu-latest 3.5
      uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-latest-3.5
    - run: mv dist-ubuntu-latest-3.5/* dist/

    - name: Stage ubuntu-latest 3.6
      uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-latest-3.6
    - run: mv dist-ubuntu-latest-3.6/* dist/

    - name: Stage ubuntu-latest 3.7
      uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-latest-3.7
    - run: mv dist-ubuntu-latest-3.7/* dist/

    - name: Stage ubuntu-latest 3.8
      uses: actions/download-artifact@v1
      with:
        name: dist-ubuntu-latest-3.8
    - run: mv dist-ubuntu-latest-3.8/* dist/

    - name: Stage macos-latest 3.5
      uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest-3.5
    - run: mv dist-macos-latest-3.5/* dist/

    - name: Stage macos-latest 3.6
      uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest-3.6
    - run: mv dist-macos-latest-3.6/* dist/

    - name: Stage macos-latest 3.7
      uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest-3.7
    - run: mv dist-macos-latest-3.7/* dist/

    - name: Stage macos-latest 3.8
      uses: actions/download-artifact@v1
      with:
        name: dist-macos-latest-3.8
    - run: mv dist-macos-latest-3.8/* dist/

    - name: Upload using twine
      run: |
        pip install twine
        echo Uploading dist files
        ls -al dist
